<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../UserDirectory.Application/UserDirectory.Application.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" /></ItemGroup></Project>
