import { FormEvent, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { usersApi } from '../api/users';
const initial = { name: '', age: '', city: '', state: '', pincode: '' };
type Errors = Partial<Record<keyof typeof initial, string>>;
function validate(v: typeof initial): Errors { const e: Errors = {}; if (v.name.trim().length < 2 || v.name.trim().length > 100) e.name = 'Name must be 2–100 characters.'; const age = Number(v.age); if (!v.age.trim() || !Number.isInteger(age) || age < 0 || age > 120) e.age = 'Age must be an integer from 0–120.'; if (!v.city.trim()) e.city = 'City is required.'; if (!v.state.trim()) e.state = 'State is required.'; if (v.pincode.trim().length < 4 || v.pincode.trim().length > 10) e.pincode = 'Pincode must be 4–10 characters.'; return e; }
export function AddPage({ onSuccess }: { onSuccess: (message: string) => void }) { const [values, setValues] = useState(initial); const [errors, setErrors] = useState<Errors>({}); const [saving, setSaving] = useState(false); const [serverError, setServerError] = useState(''); const navigate = useNavigate();
 const submit = async (ev: FormEvent) => { ev.preventDefault(); const e = validate(values); setErrors(e); if (Object.keys(e).length) return; setSaving(true); setServerError(''); try { await usersApi.create({ name: values.name.trim(), age: Number(values.age), city: values.city.trim(), state: values.state.trim(), pincode: values.pincode.trim() }); onSuccess('User added successfully.'); navigate('/'); } catch (err) { setServerError(err instanceof Error ? err.message : 'Unable to create user'); } finally { setSaving(false); } };
 return <main className="container narrow"><div className="page-head"><div><h1>Add user</h1><p>Create a new directory entry.</p></div></div>{serverError && <div className="alert error">{serverError}</div>}<form onSubmit={submit} noValidate className="card"><Field label="Name" name="name" value={values.name} error={errors.name} onChange={v => setValues({...values,name:v})} /><Field label="Age" name="age" type="number" value={values.age} error={errors.age} onChange={v => setValues({...values,age:v})} /><Field label="City" name="city" value={values.city} error={errors.city} onChange={v => setValues({...values,city:v})} /><Field label="State" name="state" value={values.state} error={errors.state} onChange={v => setValues({...values,state:v})} /><Field label="Pincode" name="pincode" value={values.pincode} error={errors.pincode} onChange={v => setValues({...values,pincode:v})} /><button className="button" disabled={saving}>{saving ? 'Saving…' : 'Add user'}</button></form></main>; }
function Field({label,name,value,error,onChange,type='text'}:{label:string;name:string;value:string;error?:string;onChange:(v:string)=>void;type?:string}) { return <label className="field">{label}<input name={name} type={type} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined}/>{error && <span id={`${name}-error`} className="field-error">{error}</span>}</label>; }
